name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1.0.6
        with:
          version: nightly

      - name: Install node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16

      - name: Clone repo with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: Install yarn
      #   run: npm i -g yarn

      - name: Install dependencies
        run: make

      - name: Show Foundry config
        run: forge config
        
      - name: Check contracts are linted
        run: yarn lint:check

      - name: Run tests
        run: make test
